import random

def calculate_unity_layout(semantic_objects, mapped_assets, database):

    x_min = -10.0
    x_max = 10.0
    z_min = -10.0
    z_max = 10.0
    
    # Converts the database into a fast dictionary for size lookups
    db_dict = {item["db_id"]: item for item in database}
    
    unity_payload = {
        "objects_to_spawn": []
    }

    for match in mapped_assets:
        # If the Asset Agent discarded the item (returned None).
        if not match.matched_db_id:
            continue
            
        # Gets physical dimensions from the database (Assuming [x, y, z] in meters)
        # If 'size' is not registered, assumes 1x1x1 for safety
        asset_info = db_dict.get(match.matched_db_id, {})
        obj_size = asset_info.get("size", [1.0, 1.0, 1.0]) 
        
        # Finds the spatial rules generated by the Semantic Agent for this instance_id
        semantic_info = next((obj for obj in semantic_objects if obj.instance_id == match.instance_id), None)
        if not semantic_info:
            continue
            
        relation = semantic_info.relation
        parent_id = semantic_info.parent_id

        # Fetches the "Parent" object size to calculate the distance
        parent_size = [0.0, 0.0, 0.0]
        if parent_id != "world":
            # Finds out the parent's db_id
            parent_match = next((m for m in mapped_assets if m.instance_id == parent_id), None)
            if parent_match and parent_match.matched_db_id:
                parent_info = db_dict.get(parent_match.matched_db_id, {})
                parent_size = parent_info.get("size", [1.0, 1.0, 1.0])

        # --- SPATIAL CALCULATION (Local Coordinates) ---
        pos_x, pos_y, pos_z = 0.0, 0.0, 0.0
        margin = 0.05 

        if relation == "none" or parent_id == "world":
            pos_x = random.uniform(x_min, x_max)
            pos_z = random.uniform(z_min, z_max)

        elif relation == "on_top":
            # Places on top: Y receives the total height (Y) of the parent.
            pos_y = parent_size[1]
            
        elif relation == "next_to":
            # Places next to: Half of parent's X + Half of child's X + Margin
            pos_x = (parent_size[0] / 2.0) + (obj_size[0] / 2.0) + margin
            
        elif relation == "in_front":
            # Places in front: (Negative Z axis in Unity)
            pos_z = -((parent_size[2] / 2.0) + (obj_size[2] / 2.0) + margin)
            
        elif relation == "back":
            # Places in back: (Positive Z axis)
            pos_z = (parent_size[2] / 2.0) + (obj_size[2] / 2.0) + margin

        # Adds the finalized object to the list
        unity_payload["objects_to_spawn"].append({
            "instance_id": match.instance_id,
            "prefab_id": match.matched_db_id,
            "parent_id": parent_id,
            "position": {"x": round(pos_x, 3), "y": round(pos_y, 3), "z": round(pos_z, 3)},
            "rotation": {"x": 0.0, "y": 0.0, "z": 0.0},
            "scale": {"x": 1.0, "y": 1.0, "z": 1.0}
        })

    return unity_payload