from pydantic import BaseModel, Field, model_validator
from typing import Literal




# --- FastAPI ---
class UnityMessage(BaseModel):
    content: str


# --- 1.1 Structured Output From the Semantic Agent --- 

class SceneObject(BaseModel):
    instance_id: str = Field(description="Unique identifier, e.g., 'main_desk', 'coffee_cup_1'")
    named_asset: str = Field(description="Name of the object to search for in the dataset, e.g., 'Desk', 'Chair', 'Tree'")
    parent_id: str = Field(description="The instance_id of the object this is related to. Use 'world' if it rests on the floor and is not related to other objects.")
    relation: Literal['on_top', 'in_front', 'back', 'next_to', 'none'] = Field(
        description="Spatial relationship to the related object. Use 'none' if parent_id is 'world'.")

    @model_validator(mode='after')
    def enforce_world_relation(self):
      # If the LLM makes a mistake and sets a relation for 'world', we force it to 'none'
      if self.parent_id == 'world':
           self.relation = 'none'
      return self

class SceneGraph(BaseModel):
    theme: str = Field(description="The general theme deduced from the environment (e.g., 'Study Room', 'Bedroom', 'Forest')")
    objects: list[SceneObject] = Field(description="List of 5 to 10 objects that make up this environment.")

# -----------------------------------------------

# --- 1.2 Structured Output From the Asset Agent --- 

class MappedAsset(BaseModel):
    instance_id: str = Field(description="The 'instance_id' generated by the Semantic Agent (e.g., 'monitor_1')")
    requested_asset: str = Field(description="The name of the asset requested by the Semantic Agent")
    matched_db_id: str | None = Field(description="The exact 'db_id' from the Database that best matches. Return null (None) if there is nothing remotely similar.")
    reason: str = Field(description="A very short explanation of why this item was chosen or why it returned null.")

class AssetMappingReport(BaseModel):
    mappings: list[MappedAsset]

# -----------------------------------------------
